version: "3.9"

services:
    postgres-container:
        image: postgres:15
        container_name: postgres-container
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

    api:
        build: .
        container_name: ts-api
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "3000:3000"
        depends_on:
            - postgres-container
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - backend

volumes:
    pgdata:

networks:
    backend:
